version: '3.8'

services:
  postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile.development
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auction-db
      - POSTGRES_PASSWORD=pass
    image: 'auction-db'

  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    environment:
      - PORT=8091
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/auction-db
      - JS_URL=http://localhost
    image: 'auction-app'
    ports:
      - 8080:8080
    depends_on:
      - postgres
